Develop
dilaefendioglu/Artify pull request #1
Opened 2024-09-02 21:25 UTC by dilaefendioglu

2024-09-12 08:14 UTC, kerimisoffline requested changes
Eline sağlık.

2024-09-12 08:14 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/artify/utils/Extension.kt
> +fun Fragment.hideKeyboard() {
ImageViewExtention var. bu class ismide FragmentExtention olabilir

2024-09-12 08:14 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/artify/view/MainActivity.kt
> +            binding.txtLoading.visibility = if (isLoading) View.VISIBLE else View.GONE
```suggestion
            binding.txtLoading.isVisible = isLoading
```

2024-09-12 08:14 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/artify/view/MainActivity.kt
> +            binding.txtError.visibility = if (hasError) View.VISIBLE else View.GONE
```suggestion
            binding.txtError.isVisible = hasError
```

2024-09-12 08:14 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/artify/view/fragment/SignupFragment.kt
> +            auth.createUserWithEmailAndPassword(email, password)
Firebase veritabanı isteklerini viewmodel üzerinden yapabilir miyiz?

2024-09-13 07:08 UTC, TamerSarioglu approved these changes
:D Eline sağlık

2024-09-13 07:10 UTC, kerimisoffline approved these changes

2024-09-13 07:12 UTC, merged